### ISSUE TITLE
ESP32 + Длинная линия (20м) : ошибка опроса

### ISSUE THREAD

**Issue by AntonTumilovich** [GyverLibs/microDS18B20#11]
Добрый день!

Версия библиотеки : v3.10
Схема подключения : ESP32 gpio pin + 10 kOm (pullup) => UTP 20м => DS18b20 по трехпроводной схеме (vcc, gnd, data)
Код : Опрос одного датчика на одном пине раз в 15 сек : 

Инициализация :
  #include <microDS18B20.h>
  MicroDS18B20<SENSOR_PIN> DS18b20_Sensor_Port(false);

Опрос :
  DS18b20_Sensor_Port_1.requestTemp(); read_temp = DS18b20_Sensor_Port_1.getTemp();

Проблема : 
На коротком отрезке UTP 1-3м читает датчик отлично
На отрезке в 20м(кабель смотан в бухту) и чипе ESP32 не читает совсем
При том :
Этот код и схема подключения отлично работает на atmega328 (а обычная библиотека DallasTemperature не может прочитать данные)
Эта схема  подключения отлично работает на ESP32 + обычная библиотека DallasTemperature

На коротких линиях работает при любой схеме, любом чипе и на любой библиотеке

**Comment by GyverLibs** [comment]
Ну и опрос делается неправильно, смотрите документацию, примеры
