### ISSUE TITLE
Не читает датчики с новой версией библиотеки Arduino ESP32 Version 2.0.3

### ISSUE THREAD

**Issue by voluser** [GyverLibs/microDS18B20#15]
До этого стояла версия платы 2.0.2  , после обновления на 2,03  перстала работать библиотека microDS18B20. Моя плата ESP32-DevKitC V4 модуль ESP32-WROOM-32D. В менеджере плат выбран модуль ESP32 Dev module. Пробовал опрашивать датчики через библиотеки OneWire + DallasTemperature  - все отлично . Только после отката версии платы на Arduino ESP32 Version 2.0.2 , заработала и microDS18B20 .

**Comment by GyverLibs** [comment]
И снова индусы что то сломали или переделали в IO, как же это надоело...

**Comment by DenysChuhlib** [comment]
У меня тоже самое с переходом с esp8266 на esp32 не работает.

**Comment by DenysChuhlib** [comment]
Это люди отправляли свои ришения проблем и кто-то накосячил

**Comment by GyverLibs** [comment]
А?

**Comment by DenysChuhlib** [comment]
Если глянуть в историю исправлений то там куча людей что-то пофиксили.

**Comment by GyverLibs** [comment]
Это были Фиксики. В любом случае, если оно перестало работать - IO в esp32 стал работать как минимум на 100-300 микросекунд медленнее, это п.дец) пока нет возможности, а так планирую залезть в эту либу с лог анализатором и нормально всё руками потрогать

**Comment by DenysChuhlib** [comment]
Хорошо

**Comment by PcbSmd** [comment]
Насколько я понимаю, пока нет решения? Модуль ESP32-WROOM-32E, PlatformIO IDE v3.0.0. Библиотека microDS18B20 не видит датчик, но, как сказано выше - OneWire + DallasTemperature работают.

**Comment by DenysChuhlib** [comment]
Да

**Comment by GyverLibs** [comment]
да толку фиксить, всё равно сломают) ждём стабильного ядра

**Comment by AntonMalygin** [comment]
> да толку фиксить, всё равно сломают) ждём стабильного ядра

Блин я думал я что-то не так напаял...действительно az-delivery-devkit-v4 на данный момент 28апр.23г пока не работает библиотека. Жаль..Так приятно использовать ваши библиотеки в своих проектах.

**Comment by GyverLibs** [comment]
DS18B20 планируется крупное обновление, расширение функционала, но пока неизвестно когда к сожалению. С esp32 проблемы были изначально, они несколько раз решались но с новыми обновлениями ядра опять всё ломается. Несмотря на то, что библиотека написана невероятно примитивно - протокол OneWire реализован на digitalWrite/Read и задержках, что должно работать на любой Ардуино-совместимой платформе

**Comment by sigmashig** [comment]
Не заработало на  ESP32. Посмотрел реализацию paulstoffregen... Или он намудрил или на тривиальных задержках, в условиях многоядерности, уже не получится написать. У него постоянные отключения/включения ISR. Возможно, эти преывания и мешают - сбивают задержки.

**Comment by GyverLibs** [comment]
Прелести RTOS :)

**Comment by uzi18** [comment]
For ESP32 use OneWireNg, it is rewritten from scratch.
