### ISSUE TITLE
Динамическое задание pin

### ISSUE THREAD

**Issue by sigmashig** [GyverLibs/microDS18B20#21]
Замечательная библиотека. Ничего лишнего. Но... Номер пина, на котором висит термометр задается в темплейте класса. А что делать, если этот пин динамический и определяется уже в середине работы? Особой необходимости иметь его именно в темплейте нет. Было бы очень хорошо или принимать этот пин как параметр конструктора или, еще лучше - добавить метод init, который уже и установит режим работы отдельно от конструктора. Очень часто надо создать класс, а потом его проинициализировать. Я понимаю, что можно скопировать код к себе и "подправить", но это:
1. Неэтично
2. Непрактично (остаешься без багфиксов).

**Comment by GyverLibs** [comment]
да, библиотека доделана за первым автором. Задумывалась именно МИКРО версия, так что позже планирую выпустить более расширенную версию с убранными излишками в темплейте
