### ISSUE TITLE
Не Проблема, но вопрос )

### ISSUE THREAD

**Issue by vadlis** [GyverLibs/microDS18B20#23]
Просто интересно - что мешает добавить флаг в readTemp и по этому флагу вызывать requestTemp в концу функции? тогда код примеров будет покороче )

**Comment by GyverLibs** [comment]
Ничего не понял

**Comment by vadlis** [comment]
float getTemp(uint8_t idx = 0, bool request = false) {
 ...
 if (request) {
  requestTemp(idx);
  }
}

тогда в примерах можно убрать код с requestTemp.

**Comment by GyverLibs** [comment]
Это нарушит логику работы с датчиком. Температуру нужно запросить, а ответ будет готов спустя некоторое время вплоть до 1 секунды

**Comment by vadlis** [comment]
понятно

**Comment by vadlis** [comment]
хотя не очень )). код из примера:

https://github.com/GyverLibs/microDS18B20/blob/main/examples/async_read_many/async_read_many.ino#L35-L45

в этом случае requestTemp просто переместится из скетча в библиотеку.

**Comment by GyverLibs** [comment]
Сделай форк с более короткой записью. В данной библиотеке request это отдельная операция на усмотрение юзера

**Comment by vadlis** [comment]
Ну собсно флаг тоже был бы опциональным. Ну да ладно - на нет и суда нет ))
