### ISSUE TITLE
NodeMCU v3  DS_rawToInt && DS_rawToFloat

### ISSUE THREAD

**Issue by RuDennn** [GyverLibs/microDS18B20#6]
Если в коде присутствуют функции DS_rawToInt || DS_rawToFloat вылетает ошибка collect2: error: ld returned 1 exit status.

### код:
>[https://pastebin.com/CpEV1gK3](url)

### лог:
>[https://pastebin.com/sBYGcdeJ](url)

**Comment by RuDennn** [comment]
Даже пример raw_and_calc не компилируется.

**Comment by GyverLibs** [comment]
Спасибо, в сегодняшнем большом обновлении починю

**Comment by GyverLibs** [comment]
исправлено
