### ISSUE TITLE
динамическое создание объекта MicroDS18B20

### ISSUE THREAD

**Issue by gonzzzales** [GyverLibs/microDS18B20#7]
Подскажите пожалуйста, как можно переделать библиотеку, чтобы можно было динамически создать объект и присвоить ему пин.
По типу 
MicroDS18B20* sensor;
sensor= new MicroDS18B20;
sensor->setPin(DS_PIN);

**Comment by GyverLibs** [comment]
а зачем её переделывать?
```cpp
MicroDS18B20<2> *sensor;
// ...
sensor = new MicroDS18B20<2>;
// ...
sensor->requestTemp();
```
